trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - Tasks/*

pr: none

pool:
  name: Default

stages:
- stage: Build
  jobs:
  - template: templates/build.yml
    parameters:
      task: true
      extension: true

- stage: Preview
  dependsOn:
  - Build
  jobs:
  - template: templates/preview.yml
    parameters:
      environmentName: Marketplace

- stage: Release
  dependsOn:
  - Build
  - Preview
  jobs:
  - template: templates/release.yml
    parameters:
      environmentName: Marketplace
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
