trigger:
- master

pr: none

pool:
  vmImage: windows-latest

steps:
- task: PowerShell@2
  displayName: Run Tests
  inputs:
    filePath: CI/Scripts/Validate.ps1
    arguments: -Path PublisherV1/Tests

- task: PublishTestResults@2
  displayName: Publish Test Results
  inputs:
    testResultsFormat: NUnit
    testResultsFiles: "**/TestResults.xml"
  condition: succeededOrFailed()

- task: PowerShell@2
  displayName: Package Artifact
  inputs:
    filePath: Package.ps1
    arguments: -Path $(Build.SourcesDirectory) -Output $(Build.StagingDirectory)

- task: PublishBuildArtifacts@1
  displayName: Publish Modules
  inputs:
    PathtoPublish: $(Build.StagingDirectory)/Extension/PublisherV1/ps_modules
    ArtifactName: Modules

- task: PublishBuildArtifacts@1
  displayName: Publish Extension
  inputs:
    PathtoPublish: $(Build.StagingDirectory)/Extension
    ArtifactName: Extension
